FROM node:16

USER root

WORKDIR /user/app/src

RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install git -y

RUN git clone https://github.com/zune2222/Busan_7th_ICT_Hackathon_1978_BackEnd.git /user/app/src
RUN git pull origin main

RUN npm i --force
RUN npm install --location=global pm2
RUN npm run build
CMD ["npx","pm2","start","dist/main.js","--name","server"]