FROM node:16

USER root

WORKDIR /usr/app/src

RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install -y git nano
RUN git clone https://github.com/zune2222/Busan_7th_ICT_Hackathon_1978_BackEnd.git /usr/app/src
RUN git checkout -B main
RUN git pull origin main

COPY ./.env /usr/app/src/.env

RUN npm install
RUN npm run build