FROM mariadb

ENV MYSQL_ROOT_PASSWORD qwer1234

WORKDIR /etc/mysql/setDB

COPY ./setDB.sql /etc/mysql/setDB/setDB.sql

RUN echo lower_case_table_names=1 >> /etc/mysql/conf.d/docker.cnf
RUN echo default-time-zone='+9:00' >> /etc/mysql/conf.d/docker.cnf